name: Install
description: "Set up the environment for the project"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile

#    - uses: nrwl/nx-set-shas@v4

    - if: github.ref != 'refs/heads/main'
      shell: bash
      run: git rev-parse --verify main || git remote set-branches origin main && git fetch --depth 1 origin main && git branch main origin/main
